volumes:
  api-node-modules:
    name: ${PROJECT_TAG}-api-node-modules
  mailer-node-modules:
    name: ${PROJECT_TAG}-mailer-node-modules
  panel-react-node-modules:
    name: ${PROJECT_TAG}-panel-react-node-modules
  panel-vue-node-modules:
    name: ${PROJECT_TAG}-panel-vue-node-modules

services:
  grafana:
    restart: no
    env_file:
      - .env
    volumes:
      - ./infrastructure/grafana/provisioning:/etc/grafana/provisioning
      - ./infrastructure/grafana/dashboards:/var/lib/grafana/dashboards
  prometheus:
    restart: no
    env_file:
      - .env
    volumes:
      - ./infrastructure/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  rabbitmq:
    restart: no
    ports:
      - 127.0.0.1:15672:15672
    env_file:
      - .env
    volumes:
      - ./infrastructure/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf

  postgres:
    restart: no
    ports:
      - 127.0.0.1:${POSTGRES_PORT}:${POSTGRES_PORT}
    env_file:
      - .env
    volumes:
      - ./infrastructure/postgres/postgresql.conf:/etc/postgresql/postgresql.conf
  postgres-exporter:
    restart: no

  redis:
    restart: no
    ports:
      - 127.0.0.1:${REDIS_PORT}:${REDIS_PORT}
    env_file:
      - .env
    volumes:
      - ./infrastructure/redis/redis-stack.conf:/redis-stack.conf
  redis-exporter:
    restart: no

  nginx:
    restart: no
    env_file:
      - .env
    volumes:
      - ./infrastructure/nginx/html:/usr/share/nginx/html
      - ./infrastructure/nginx/ssl:/usr/share/nginx/ssl
      - ./infrastructure/nginx/snippets:/etc/nginx/snippets
      - ./infrastructure/nginx/templates:/etc/nginx/templates
  nginx-exporter:
    restart: no

  api:
    build:
      target: development
    restart: no
    env_file:
      - .env
    volumes:
      - ./shared:/usr/src/app/shared
      - ./apps/backend/api:/usr/src/app/apps/backend/api
      - api-node-modules:/usr/src/app/node_modules
  mailer:
    build:
      target: development
    restart: no
    env_file:
      - .env
    volumes:
      - ./shared:/usr/src/app/shared
      - ./apps/backend/mailer:/usr/src/app/apps/backend/mailer
      - mailer-node-modules:/usr/src/app/node_modules
  panel-react:
    build:
      target: development
    restart: no
    env_file:
      - .env
    volumes:
      - ./shared:/usr/src/app/shared
      - ./apps/frontend/panel-react:/usr/src/app/apps/frontend/panel-react
      - panel-react-node-modules:/usr/src/app/node_modules
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 4G
        reservations:
          cpus: '1.0'
          memory: 1G
  panel-vue:
    build:
      target: development
    restart: no
    env_file:
      - .env
    volumes:
      - ./shared:/usr/src/app/shared
      - ./apps/frontend/panel-vue:/usr/src/app/apps/frontend/panel-vue
      - panel-vue-node-modules:/usr/src/app/node_modules
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 4G
        reservations:
          cpus: '1.0'
          memory: 1G
